jobs:
  build:
    name: Build
    needs:
      - checks
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v4"
        with:
          submodules: 'true'
      - name: "~/.sbt\n\"~/.cache/coursier\"\n cache"
        uses: "actions/cache@v4"
        with:
          key: "${{ runner.os }}-sbt-${{ hashFiles('build.sbt', 'project/plugins.sbt', 'project/build.properties') }}"
          path: |
            ~/.sbt
            "~/.cache/coursier"
          restore-keys: |
            ${{ runner.os }}-sbt
      - name: "java ${{ matrix.java}} setup"
        uses: "actions/setup-java@v1.4.3"
        with:
          architecture: x64
          java-package: jdk
          java-version: "${{ matrix.java}}"
      - name: Setup sbt launcher
        uses: sbt/setup-sbt@v1
      - run: "bash run_sbt.sh -DJDK_VERSION=${{ matrix.java}} \"++${{ matrix.scala}} test\""
    strategy:
      matrix:
        java:
          - '17.0.9'
        scala:
          - '2.13.13'
          - '3.3.3'
          - '3.4.0'
  checks:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v4"
        with:
          submodules: 'true'
      - name: "~/.sbt\n\"~/.cache/coursier\"\n cache"
        uses: "actions/cache@v4"
        with:
          key: "${{ runner.os }}-sbt-${{ hashFiles('build.sbt', 'project/plugins.sbt', 'project/build.properties') }}"
          path: |
            ~/.sbt
            "~/.cache/coursier"
          restore-keys: |
            ${{ runner.os }}-sbt
      - name: java 17 setup
        uses: "actions/setup-java@v1.4.3"
        with:
          architecture: x64
          java-package: jdk
          java-version: '17'
      - name: Setup sbt launcher
        uses: sbt/setup-sbt@v1
      - run: sbt scalafmtCheckAll scalafmtSbtCheck
name: build_and_test
on:
  pull_request: {}
  push: {}
